# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml
require: rubocop/cop/internal_affairs

AllCops:
  Includes:
    - Rakefile
    - config.ru
    - '**/Gemfile'
  Excludes:
    - db/**
    - config/**
    - script/**

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false

Style/DocumentationMethod:
  RequireForNonPublicMethods: false
  Enabled: false

