# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
default: &default
 adapter: mysql2
 encoding: utf8
 reconnect: false
 pool: 25
 username: ubuntu
 port: 3306
 socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: micro_blog_development

test:
  <<: *default
  database: micro_blog_test

production:
  <<: *default
  database: micro_blog_production
